<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>SmeAccounting.Modules.Organization.Infrastructure</RootNamespace>
    <AssemblyName>SmeAccounting.Modules.Organization.Infrastructure</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Application/SmeAccounting.Modules.Organization.Application.csproj" />
  </ItemGroup>

</Project>
