using Microsoft.EntityFrameworkCore;
using SmeAccounting.Domain.Entities;
using SmeAccounting.Domain.ValueObjects;

namespace SmeAccounting.Infrastructure.Persistence.Seeds;

public static class SystemSecuritySeed
{
    public static void Apply(ModelBuilder modelBuilder)
    {
        // VoucherType defaults are per-company, not seeded globally.
        // DocumentNumberingSeries defaults are per-company per voucher type.
        // This seed provides reference data for the first demo company Id = 1.
        // In production, seed via CreateCompanyWithDefaultsCommandHandler.

        // Example for CompanyId = 1
        // var companyId = 1;

        var voucherTypes = new[]
        {
            new { Code = "RCPT", Name = "Receipt", Category = VoucherCategory.Receipt },
            new { Code = "PMT",  Name = "Payment", Category = VoucherCategory.Payment },
            new { Code = "JNRL", Name = "Journal", Category = VoucherCategory.Journal },
            new { Code = "ADJ",  Name = "Adjustment", Category = VoucherCategory.Adjustment },
            new { Code = "OPEN", Name = "Opening", Category = VoucherCategory.Opening }
        };

        // VoucherType seed placeholder – actual Ids generated by EF
        // HasData requires explicit Ids. In practice, use Application service to create per company.
        // This method is intentionally left as a template; prefer domain service seeding.

        // DocumentNumberingSeries template
        // new DocumentNumberingSeries(companyId, voucherTypeId, prefix, 1, 6, true)
    }
}
