<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>SmeAccounting.Modules.Authorization.Application</RootNamespace>
    <AssemblyName>SmeAccounting.Modules.Authorization.Application</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Domain/SmeAccounting.Modules.Authorization.Domain.csproj" />
    <ProjectReference Include="../../../SmeAccounting.Application/SmeAccounting.Application.csproj" />
    <ProjectReference Include="../../../SmeAccounting.SharedKernel/SmeAccounting.SharedKernel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" />
  </ItemGroup>

</Project>
