<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>SmeAccounting.Modules.Identity.Infrastructure</RootNamespace>
    <AssemblyName>SmeAccounting.Modules.Identity.Infrastructure</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Application/SmeAccounting.Modules.Identity.Application.csproj" />
    <ProjectReference Include="../Domain/SmeAccounting.Modules.Identity.Domain.csproj" />
    <ProjectReference Include="../../../SmeAccounting.Infrastructure/SmeAccounting.Infrastructure.csproj" />
  </ItemGroup>

</Project>
