<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>SmeAccounting.Modules.FinancialReporting.Domain</RootNamespace>
    <AssemblyName>SmeAccounting.Modules.FinancialReporting.Domain</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../SmeAccounting.Domain/SmeAccounting.Domain.csproj" />
    <ProjectReference Include="../../../SmeAccounting.SharedKernel/SmeAccounting.SharedKernel.csproj" />
  </ItemGroup>

</Project>
