"""add cost_centers table

Revision ID: 0bc4d5a35684
Revises: 7f26e5ec1793
Create Date: 2026-08-26 11:17:32.389641
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '0bc4d5a35684'
down_revision = '7f26e5ec1793'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cost_centers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('audit_checksum', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_centers_company_id'), 'cost_centers', ['company_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fixed_assets',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('company_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('asset_code', sa.VARCHAR(length=30), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('category', sa.VARCHAR(length=20), server_default=sa.text("'huu_hinh'"), nullable=True),
    sa.Column('original_cost', sa.NUMERIC(precision=18, scale=2), nullable=False),
    sa.Column('acquisition_date', sa.DATE(), nullable=False),
    sa.Column('useful_life_months', sa.INTEGER(), nullable=False),
    sa.Column('depreciation_account', sa.VARCHAR(length=10), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text("'1'"), nullable=True),
    sa.Column('accumulated_depreciation', sa.NUMERIC(precision=18, scale=2), server_default=sa.text("'0'"), nullable=True),
    sa.Column('checksum', sa.VARCHAR(length=64), server_default=sa.text("('')"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fixed_assets_company_id'), 'fixed_assets', ['company_id'], unique=False)
    op.drop_index(op.f('ix_cost_centers_company_id'), table_name='cost_centers')
    op.drop_table('cost_centers')
    # ### end Alembic commands ###
