"""initial schema — all bricks

Revision ID: 2d7adc359b8c
Revises: 
Create Date: 2026-08-25 15:08:25.667794
"""
from __future__ import annotations

import sqlalchemy as sa

from alembic import op

revision = '2d7adc359b8c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('mst', sa.String(length=20), nullable=False),
    sa.Column('headquarters_address', sa.String(length=500), nullable=False),
    sa.Column('legal_representative', sa.String(length=255), nullable=False),
    sa.Column('business_reg_number', sa.String(length=100), nullable=True),
    sa.Column('business_reg_date', sa.Date(), nullable=True),
    sa.Column('business_fields', sa.Text(), nullable=True),
    sa.Column('company_type', sa.String(length=30), nullable=False),
    sa.Column('accounting_regime', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('fiscal_year_start_month', sa.Integer(), nullable=False),
    sa.Column('fiscal_year_start_day', sa.Integer(), nullable=False),
    sa.Column('responsible_accountant_name', sa.String(length=255), nullable=False),
    sa.Column('responsible_accountant_license', sa.String(length=100), nullable=True),
    sa.Column('tax_agency', sa.String(length=300), nullable=False),
    sa.Column('controlling_tax_office', sa.String(length=300), nullable=False),
    sa.Column('bhxh_code', sa.String(length=50), nullable=True),
    sa.Column('bhxh_agency', sa.String(length=300), nullable=True),
    sa.Column('authorized_capital', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=100), nullable=True),
    sa.Column('bank_accounts', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Date(), server_default=sa.text('(CURRENT_DATE)'), nullable=True),
    sa.Column('updated_at', sa.Date(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('config_version', sa.Integer(), nullable=False),
    sa.Column('legal_reviewed_at', sa.Date(), nullable=True),
    sa.Column('legal_reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('mst_changed_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mst')
    )
    op.create_table('document_numbering_series',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('prefix', sa.String(length=20), nullable=False),
    sa.Column('next_sequence', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('max_sequences', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'prefix', name='uq_series_company_prefix')
    )
    op.create_index(op.f('ix_document_numbering_series_company_id'), 'document_numbering_series', ['company_id'], unique=False)
    op.create_table('payment_terms',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('due_days', sa.Integer(), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name', name='uq_payment_term_company_name')
    )
    op.create_index(op.f('ix_payment_terms_company_id'), 'payment_terms', ['company_id'], unique=False)
    op.create_table('pt_approval_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('request_type', sa.String(length=30), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('requested_by', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('decided_by', sa.String(length=36), nullable=True),
    sa.Column('decided_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pt_approval_requests_company_id'), 'pt_approval_requests', ['company_id'], unique=False)
    op.create_index(op.f('ix_pt_approval_requests_status'), 'pt_approval_requests', ['status'], unique=False)
    op.create_index(op.f('ix_pt_approval_requests_target_id'), 'pt_approval_requests', ['target_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=True),
    sa.Column('before_value', sa.JSON(), nullable=True),
    sa.Column('after_value', sa.JSON(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('prev_checksum', sa.String(length=64), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('ts_iso', sa.String(length=64), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_actor_id'), 'audit_events', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_events_checksum'), 'audit_events', ['checksum'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_id'), 'audit_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_type'), 'audit_events', ['entity_type'], unique=False)
    op.create_table('fiscal_periods',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('fiscal_year_id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('locked_by', sa.String(length=36), nullable=True),
    sa.Column('lock_reason', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fiscal_periods_company_id'), 'fiscal_periods', ['company_id'], unique=False)
    op.create_index(op.f('ix_fiscal_periods_fiscal_year_id'), 'fiscal_periods', ['fiscal_year_id'], unique=False)
    op.create_table('fiscal_years',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fiscal_years_company_id'), 'fiscal_years', ['company_id'], unique=False)
    op.create_table('accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('parent_code', sa.String(length=16), nullable=True),
    sa.Column('normal_balance', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('regime', sa.String(length=12), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_code'), 'accounts', ['code'], unique=False)
    op.create_index(op.f('ix_accounts_company_id'), 'accounts', ['company_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('number', sa.String(length=30), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('customer_name', sa.String(length=200), nullable=False),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('vat_rate', sa.String(length=20), nullable=False),
    sa.Column('payment_term_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_company_id'), 'invoices', ['company_id'], unique=False)
    op.create_index(op.f('ix_invoices_number'), 'invoices', ['number'], unique=False)
    op.create_table('bank_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=False),
    sa.Column('account_number', sa.String(length=30), nullable=False),
    sa.Column('account_holder', sa.String(length=255), nullable=False),
    sa.Column('branch', sa.String(length=200), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_accounts_account_number'), 'bank_accounts', ['account_number'], unique=False)
    op.create_index(op.f('ix_bank_accounts_company_id'), 'bank_accounts', ['company_id'], unique=False)
    op.create_table('bank_reconciliations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('bank_account_id', sa.String(length=36), nullable=False),
    sa.Column('reconciliation_date', sa.Date(), nullable=False),
    sa.Column('statement_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('internal_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.Date(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_reconciliations_bank_account_id'), 'bank_reconciliations', ['bank_account_id'], unique=False)
    op.create_index(op.f('ix_bank_reconciliations_company_id'), 'bank_reconciliations', ['company_id'], unique=False)
    op.create_table('cash_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('opening_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('current_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_accounts_company_id'), 'cash_accounts', ['company_id'], unique=False)
    op.create_table('supplier_invoices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('supplier_name', sa.String(length=255), nullable=False),
    sa.Column('supplier_mst', sa.String(length=14), nullable=False),
    sa.Column('invoice_number', sa.String(length=30), nullable=False),
    sa.Column('invoice_symbol', sa.String(length=30), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('lines', sa.JSON(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('vat_deductible', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('vat_non_deductible', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_payment', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=10), nullable=False),
    sa.Column('payment_proof', sa.Boolean(), nullable=False),
    sa.Column('deductibility', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_invoices_company_id'), 'supplier_invoices', ['company_id'], unique=False)
    op.create_index(op.f('ix_supplier_invoices_supplier_mst'), 'supplier_invoices', ['supplier_mst'], unique=False)
    op.create_table('system_settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('vat_rates', sa.JSON(), nullable=False),
    sa.Column('e_invoice_series', sa.JSON(), nullable=False),
    sa.Column('config_version', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_settings_company_id'), 'system_settings', ['company_id'], unique=False)
    op.create_table('tax_rate_windows',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('rate_pct', sa.Integer(), nullable=False),
    sa.Column('fraction', sa.String(length=10), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('decree_ref', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('currencies',
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('decimal_places', sa.Integer(), nullable=False),
    sa.Column('is_base', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('exchange_rates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('rate_type', sa.String(length=10), nullable=False),
    sa.Column('rate_date', sa.Date(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('source', sa.String(length=12), nullable=False),
    sa.Column('actor', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exchange_rates_currency_code'), 'exchange_rates', ['currency_code'], unique=False)
    op.create_index(op.f('ix_exchange_rates_rate_date'), 'exchange_rates', ['rate_date'], unique=False)
    op.create_index(op.f('ix_exchange_rates_rate_type'), 'exchange_rates', ['rate_type'], unique=False)
    op.create_table('revaluation_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('rate_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('entries', sa.JSON(), nullable=False),
    sa.Column('reversal_entries', sa.JSON(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('approver', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revaluation_runs_company_id'), 'revaluation_runs', ['company_id'], unique=False)
    op.create_index(op.f('ix_revaluation_runs_status'), 'revaluation_runs', ['status'], unique=False)
    op.create_table('vouchers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('number', sa.String(length=30), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('lines', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vouchers_company_id'), 'vouchers', ['company_id'], unique=False)
    op.create_index(op.f('ix_vouchers_number'), 'vouchers', ['number'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_vouchers_number'), table_name='vouchers')
    op.drop_index(op.f('ix_vouchers_company_id'), table_name='vouchers')
    op.drop_table('vouchers')
    op.drop_index(op.f('ix_revaluation_runs_status'), table_name='revaluation_runs')
    op.drop_index(op.f('ix_revaluation_runs_company_id'), table_name='revaluation_runs')
    op.drop_table('revaluation_runs')
    op.drop_index(op.f('ix_exchange_rates_rate_type'), table_name='exchange_rates')
    op.drop_index(op.f('ix_exchange_rates_rate_date'), table_name='exchange_rates')
    op.drop_index(op.f('ix_exchange_rates_currency_code'), table_name='exchange_rates')
    op.drop_table('exchange_rates')
    op.drop_table('currencies')
    op.drop_table('tax_rate_windows')
    op.drop_index(op.f('ix_system_settings_company_id'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_supplier_invoices_supplier_mst'), table_name='supplier_invoices')
    op.drop_index(op.f('ix_supplier_invoices_company_id'), table_name='supplier_invoices')
    op.drop_table('supplier_invoices')
    op.drop_index(op.f('ix_cash_accounts_company_id'), table_name='cash_accounts')
    op.drop_table('cash_accounts')
    op.drop_index(op.f('ix_bank_reconciliations_company_id'), table_name='bank_reconciliations')
    op.drop_index(op.f('ix_bank_reconciliations_bank_account_id'), table_name='bank_reconciliations')
    op.drop_table('bank_reconciliations')
    op.drop_index(op.f('ix_bank_accounts_company_id'), table_name='bank_accounts')
    op.drop_index(op.f('ix_bank_accounts_account_number'), table_name='bank_accounts')
    op.drop_table('bank_accounts')
    op.drop_index(op.f('ix_invoices_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_company_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_accounts_company_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_code'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_fiscal_years_company_id'), table_name='fiscal_years')
    op.drop_table('fiscal_years')
    op.drop_index(op.f('ix_fiscal_periods_fiscal_year_id'), table_name='fiscal_periods')
    op.drop_index(op.f('ix_fiscal_periods_company_id'), table_name='fiscal_periods')
    op.drop_table('fiscal_periods')
    op.drop_index(op.f('ix_audit_events_entity_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_checksum'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_pt_approval_requests_target_id'), table_name='pt_approval_requests')
    op.drop_index(op.f('ix_pt_approval_requests_status'), table_name='pt_approval_requests')
    op.drop_index(op.f('ix_pt_approval_requests_company_id'), table_name='pt_approval_requests')
    op.drop_table('pt_approval_requests')
    op.drop_index(op.f('ix_payment_terms_company_id'), table_name='payment_terms')
    op.drop_table('payment_terms')
    op.drop_index(op.f('ix_document_numbering_series_company_id'), table_name='document_numbering_series')
    op.drop_table('document_numbering_series')
    op.drop_table('companies')
    # ### end Alembic commands ###
