"""add dimensions and dimension_values tables

Revision ID: e348258e2761
Revises: 0bc4d5a35684
Create Date: 2026-08-27 09:06:05.152182
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'e348258e2761'
down_revision = '0bc4d5a35684'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dimension_values',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('dimension_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('audit_checksum', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dimension_values_company_id'), 'dimension_values', ['company_id'], unique=False)
    op.create_index(op.f('ix_dimension_values_dimension_id'), 'dimension_values', ['dimension_id'], unique=False)
    op.create_table('dimensions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('audit_checksum', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dimensions_company_id'), 'dimensions', ['company_id'], unique=False)
    op.alter_column('fixed_assets', 'category',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'huu_hinh'"))
    op.alter_column('fixed_assets', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('fixed_assets', 'accumulated_depreciation',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('fixed_assets', 'checksum',
               existing_type=sa.VARCHAR(length=64),
               nullable=False,
               existing_server_default=sa.text("('')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fixed_assets', 'checksum',
               existing_type=sa.VARCHAR(length=64),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('fixed_assets', 'accumulated_depreciation',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('fixed_assets', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('fixed_assets', 'category',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'huu_hinh'"))
    op.drop_index(op.f('ix_dimensions_company_id'), table_name='dimensions')
    op.drop_table('dimensions')
    op.drop_index(op.f('ix_dimension_values_dimension_id'), table_name='dimension_values')
    op.drop_index(op.f('ix_dimension_values_company_id'), table_name='dimension_values')
    op.drop_table('dimension_values')
    # ### end Alembic commands ###
