"""Company module: CompanyModel, BankAccountModel, company_id FKs

Revision ID: 080dad0b79e8
Revises: 
Create Date: 2026-08-17 11:18:09.710530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '080dad0b79e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('mst', sa.String(length=13), nullable=False),
    sa.Column('headquarters_address', sa.String(length=500), nullable=False),
    sa.Column('legal_representative', sa.String(length=255), nullable=False),
    sa.Column('business_reg_number', sa.String(length=20), nullable=False),
    sa.Column('business_reg_date', sa.Date(), nullable=False),
    sa.Column('business_fields', sa.String(length=200), nullable=False),
    sa.Column('company_type', sa.Enum('SINGLE_LLC', 'MULTI_LLC', 'JSC', 'LISTED_JSC', 'SOLE_PROP', 'PARTNERSHIP', 'HOUSEHOLD', 'COOP', name='companytypeenum'), nullable=False),
    sa.Column('accounting_regime', sa.Enum('TT200', 'TT99', 'TT58_MICRO', 'TT133', name='accountingregimeenum'), nullable=False),
    sa.Column('fiscal_year_start_month', sa.Integer(), nullable=False),
    sa.Column('fiscal_year_start_day', sa.Integer(), nullable=False),
    sa.Column('responsible_accountant_name', sa.String(length=255), nullable=False),
    sa.Column('responsible_accountant_license', sa.String(length=50), nullable=False),
    sa.Column('tax_agency', sa.String(length=300), nullable=False),
    sa.Column('controlling_tax_office', sa.String(length=300), nullable=False),
    sa.Column('bhxh_code', sa.String(length=20), nullable=False),
    sa.Column('bhxh_agency', sa.String(length=300), nullable=False),
    sa.Column('authorized_capital', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('website', sa.String(length=200), nullable=False),
    sa.Column('short_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'DISSOLVED', name='companystatusenum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('updated_at', sa.Date(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=False),
    sa.Column('config_version', sa.Integer(), nullable=False),
    sa.Column('legal_reviewed_at', sa.Date(), nullable=True),
    sa.Column('legal_reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('mst_changed_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_legal_name'), ['legal_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_mst'), ['mst'], unique=True)

    op.create_table('bank_accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=False),
    sa.Column('account_number', sa.String(length=30), nullable=False),
    sa.Column('account_holder', sa.String(length=255), nullable=False),
    sa.Column('branch', sa.String(length=200), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bank_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bank_accounts_account_number'), ['account_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_bank_accounts_company_id'), ['company_id'], unique=False)

    op.create_table('partners',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tax_id', sa.String(length=20), nullable=True),
    sa.Column('entity_type', sa.Enum('CUSTOMER', 'SUPPLIER', 'EMPLOYEE', name='entitytypeenum'), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('tax_agency', sa.String(length=300), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('updated_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partners_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_partners_tax_id'), ['tax_id'], unique=False)

    op.create_table('vouchers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('voucher_number', sa.String(length=20), nullable=False),
    sa.Column('voucher_type', sa.Enum('RECEIPT', 'PAYMENT', 'JOURNAL_ENTRY', 'TRANSFER_SLIP', name='documenttypeenum'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'POSTED', 'LOCKED', name='voucherstatusenum'), nullable=False),
    sa.Column('voucher_date', sa.Date(), nullable=False),
    sa.Column('accounting_date', sa.Date(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('approved_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('updated_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vouchers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vouchers_voucher_number'), ['voucher_number'], unique=True)

    op.create_table('invoices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('serial', sa.String(length=20), nullable=False),
    sa.Column('invoice_number', sa.String(length=20), nullable=False),
    sa.Column('invoice_type', sa.Enum('SALES_INVOICE', 'PURCHASE_INVOICE', 'CREDIT_NOTE', 'DEBIT_NOTE', name='invoicetypeenum'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ISSUED', 'SIGNED', 'SENT_TO_CUSTOMER', 'APPROVED', 'REJECTED', 'CANCELLED', 'REPLACED', name='invoicestatusenum'), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('partner_id', sa.Uuid(), nullable=True),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('partner_name', sa.String(length=255), nullable=False),
    sa.Column('partner_tax_id', sa.String(length=20), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('vat_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=False),
    sa.Column('replaced_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('updated_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoices_invoice_number'), ['invoice_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_serial'), ['serial'], unique=False)

    op.create_table('voucher_lines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('voucher_id', sa.Uuid(), nullable=False),
    sa.Column('account_code', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('debit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('credit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('cost_center', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['voucher_id'], ['vouchers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('voucher_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_voucher_lines_account_code'), ['account_code'], unique=False)

    op.create_table('invoice_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('vat_rate', sa.Integer(), nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice_items')
    with op.batch_alter_table('voucher_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_voucher_lines_account_code'))

    op.drop_table('voucher_lines')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_serial'))
        batch_op.drop_index(batch_op.f('ix_invoices_invoice_number'))

    op.drop_table('invoices')
    with op.batch_alter_table('vouchers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vouchers_voucher_number'))

    op.drop_table('vouchers')
    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partners_tax_id'))
        batch_op.drop_index(batch_op.f('ix_partners_code'))

    op.drop_table('partners')
    with op.batch_alter_table('bank_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bank_accounts_company_id'))
        batch_op.drop_index(batch_op.f('ix_bank_accounts_account_number'))

    op.drop_table('bank_accounts')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_mst'))
        batch_op.drop_index(batch_op.f('ix_companies_legal_name'))

    op.drop_table('companies')
    # ### end Alembic commands ###
