"""system_settings_phase_1

Revision ID: 382db5a877f2
Revises: 080dad0b79e8
Create Date: 2026-08-17 14:22:01.170537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '382db5a877f2'
down_revision = '080dad0b79e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=True),
    sa.Column('before_value', sa.String(length=500), nullable=True),
    sa.Column('after_value', sa.String(length=500), nullable=True),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('changed_at', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ca_list_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ca_identifier', sa.String(length=100), nullable=False),
    sa.Column('ca_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('cert_hash', sa.String(length=64), nullable=True),
    sa.Column('expired_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ca_list_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ca_list_entries_ca_identifier'), ['ca_identifier'], unique=True)

    op.create_table('e_invoice_series',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('series_prefix', sa.String(length=20), nullable=False),
    sa.Column('next_sequence', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('ca_signer', sa.String(length=100), nullable=True),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('e_invoice_series', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_e_invoice_series_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_e_invoice_series_series_prefix'), ['series_prefix'], unique=False)

    op.create_table('period_locks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('locked_at', sa.Date(), nullable=True),
    sa.Column('locked_by_id', sa.Uuid(), nullable=True),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('period_locks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_period_locks_company_id'), ['company_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('period_locks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_period_locks_company_id'))

    op.drop_table('period_locks')
    with op.batch_alter_table('e_invoice_series', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_e_invoice_series_series_prefix'))
        batch_op.drop_index(batch_op.f('ix_e_invoice_series_company_id'))

    op.drop_table('e_invoice_series')
    with op.batch_alter_table('ca_list_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ca_list_entries_ca_identifier'))

    op.drop_table('ca_list_entries')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
