"""immutability_triggers

Revision ID: 493immutability_triggers
Revises: 382db5a877f2
Create Date: 2026-08-17 16:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '493immutability_triggers'
down_revision = '382db5a877f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add database triggers to enforce immutability (WORM) on audit_log table
    
    # Trigger to prevent UPDATE on audit_log (SQLite-compatible: RAISE ABORT)
    op.execute("""
        CREATE TRIGGER audit_log_prevent_update
        BEFORE UPDATE ON audit_log
        FOR EACH ROW
        BEGIN
            SELECT RAISE(ABORT, 'Immutability violation: audit_log records are INSERT-only and cannot be updated');
        END
    """)
    
    # Trigger to prevent DELETE on audit_log (SQLite-compatible: RAISE ABORT)
    op.execute("""
        CREATE TRIGGER audit_log_prevent_delete
        BEFORE DELETE ON audit_log
        FOR EACH ROW
        BEGIN
            SELECT RAISE(ABORT, 'Immutability violation: audit_log records are INSERT-only and cannot be deleted');
        END
    """)
    
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS audit_log_prevent_delete")
    op.execute("DROP TRIGGER IF EXISTS audit_log_prevent_update")
    # ### end Alembic commands ###
    pass
