"""sod_roles

Revision ID: 494sod_roles
Revises: 493immutability_triggers
Create Date: 2026-08-17 17:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '494sod_roles'
down_revision = '493immutability_triggers'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: SQLite does not support native DB roles (CREATE ROLE / DROP ROLE).
    # SoD (Separation of Duties) is enforced at the application layer:
    # - audit_r role check: presentation layer validates user has audit_r role for read access
    # - sa_role restriction: service layer prevents SA from accessing audit logs
    # 
    # For PostgreSQL/MySQL production deployment, uncomment:
    # op.execute("CREATE ROLE audit_r")
    # op.execute("GRANT SELECT ON audit_log TO audit_r")
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # For PostgreSQL/MySQL production deployment, uncomment:
    # op.execute("REVOKE SELECT ON audit_log FROM audit_r")
    # op.execute("DROP ROLE audit_r")
    # ### end Alembic commands ###
    pass
