"""add fiscal years accounting periods lock events

Revision ID: a1f2b3c4d5e6
Revises: b96454ef9dc8
Create Date: 2026-08-18 16:00:00.000000

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a1f2b3c4d5e6'
down_revision = 'b96454ef9dc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'fiscal_years',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('company_id', sa.Uuid(), nullable=False),
        sa.Column('year_code', sa.String(length=20), nullable=False),
        sa.Column('period_type', sa.Enum('CALENDAR', 'FISCAL_APR', 'FISCAL_JUL', 'FISCAL_OCT', name='accountingperiodtypeenum'), nullable=False),
        sa.Column('start_date', sa.Date(), nullable=False),
        sa.Column('end_date', sa.Date(), nullable=False),
        sa.Column('is_first_period', sa.Boolean(), nullable=False),
        sa.Column('status', sa.Enum('OPEN', 'LOCKED', 'YEAR_CLOSED', name='periodstatusenum'), nullable=False),
        sa.Column('opening_balance_posted', sa.Boolean(), nullable=False),
        sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('closed_by', sa.Uuid(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('company_id', 'year_code', name='uq_fiscal_year_company_code'),
    )
    op.create_index(op.f('ix_fiscal_years_company_id'), 'fiscal_years', ['company_id'], unique=False)
    op.create_table(
        'accounting_periods',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('fiscal_year_id', sa.Uuid(), nullable=False),
        sa.Column('period_number', sa.Integer(), nullable=False),
        sa.Column('label', sa.String(length=40), nullable=False),
        sa.Column('start_date', sa.Date(), nullable=False),
        sa.Column('end_date', sa.Date(), nullable=False),
        sa.Column('status', sa.Enum('OPEN', 'LOCKED', 'YEAR_CLOSED', name='periodstatusenum'), nullable=False),
        sa.Column('locked_by', sa.Uuid(), nullable=True),
        sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('lock_reason', sa.String(length=200), nullable=True),
        sa.ForeignKeyConstraint(['fiscal_year_id'], ['fiscal_years.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('fiscal_year_id', 'period_number', name='uq_period_fy_number'),
    )
    op.create_index(op.f('ix_accounting_periods_fiscal_year_id'), 'accounting_periods', ['fiscal_year_id'], unique=False)
    op.create_table(
        'period_lock_events',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('period_id', sa.Uuid(), nullable=False),
        sa.Column('action', sa.Enum('CLOSE', 'REOPEN', 'YEAR_END', name='periodlockactionenum'), nullable=False),
        sa.Column('requested_by', sa.Uuid(), nullable=False),
        sa.Column('approved_by', sa.Uuid(), nullable=True),
        sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('reason', sa.String(length=500), nullable=False),
        sa.Column('prev_checksum', sa.String(length=64), nullable=True),
        sa.Column('checksum', sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(['period_id'], ['accounting_periods.id'], ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_period_lock_events_period_id'), 'period_lock_events', ['period_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_period_lock_events_period_id'), table_name='period_lock_events')
    op.drop_table('period_lock_events')
    op.drop_index(op.f('ix_accounting_periods_fiscal_year_id'), table_name='accounting_periods')
    op.drop_table('accounting_periods')
    op.drop_index(op.f('ix_fiscal_years_company_id'), table_name='fiscal_years')
    op.drop_table('fiscal_years')
    # ### end Alembic commands ###