"""add currencies exchange rates revaluation

Revision ID: b96454ef9dc8
Revises: 494sod_roles
Create Date: 2026-08-18 14:36:04.282296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b96454ef9dc8'
down_revision = '494sod_roles'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currencies',
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('decimal_places', sa.Integer(), nullable=False),
    sa.Column('is_base', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('display_format', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ACCOUNTANT', 'CHIEF_ACCOUNTANT', 'ADMIN', 'AUDITOR', 'DIRECTOR', name='userroleenum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('exchange_rates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('rate_date', sa.Date(), nullable=False),
    sa.Column('rate_type', sa.Enum('BUY', 'SELL', 'TRANSFER', 'CENTRAL', 'BOOKING', name='ratetypeenum'), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['currency_code'], ['currencies.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('currency_code', 'rate_date', 'rate_type', name='uq_exchange_rate_currency_date_type')
    )
    with op.batch_alter_table('exchange_rates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exchange_rates_currency_code'), ['currency_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_exchange_rates_rate_date'), ['rate_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_exchange_rates_rate_type'), ['rate_type'], unique=False)

    op.create_table('fx_differences',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('account_code', sa.String(length=10), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('opening_original', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('opening_vnd', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('movements_original', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('movements_vnd', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('closing_original', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('closing_vnd', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('revaluation_adjustment', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('cumulative_difference', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['currency_code'], ['currencies.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fx_differences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fx_differences_account_code'), ['account_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_fx_differences_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fx_differences_currency_code'), ['currency_code'], unique=False)

    op.create_table('revaluation_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('rate_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'POSTED', 'REVERSED', name='revaluationstatusenum'), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('approver_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('revaluation_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_revaluation_runs_company_id'), ['company_id'], unique=False)

    op.create_table('revaluation_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('account_code', sa.String(length=10), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('balance_original', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('rate_applied', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('old_vnd', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('new_vnd', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('difference', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('posting_side', sa.Enum('DEBIT', 'CREDIT', name='postingsideenum'), nullable=True),
    sa.ForeignKeyConstraint(['currency_code'], ['currencies.code'], ),
    sa.ForeignKeyConstraint(['run_id'], ['revaluation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('revaluation_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_revaluation_entries_run_id'), ['run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('revaluation_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_revaluation_entries_run_id'))

    op.drop_table('revaluation_entries')
    with op.batch_alter_table('revaluation_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_revaluation_runs_company_id'))

    op.drop_table('revaluation_runs')
    with op.batch_alter_table('fx_differences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fx_differences_currency_code'))
        batch_op.drop_index(batch_op.f('ix_fx_differences_company_id'))
        batch_op.drop_index(batch_op.f('ix_fx_differences_account_code'))

    op.drop_table('fx_differences')
    with op.batch_alter_table('exchange_rates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exchange_rates_rate_type'))
        batch_op.drop_index(batch_op.f('ix_exchange_rates_rate_date'))
        batch_op.drop_index(batch_op.f('ix_exchange_rates_currency_code'))

    op.drop_table('exchange_rates')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('currencies')
    # ### end Alembic commands ###
