<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>SmeAccounting.Application</RootNamespace>
    <AssemblyName>SmeAccounting.Application</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmeAccounting.Domain\SmeAccounting.Domain.csproj" />
    <ProjectReference Include="..\SmeAccounting.SharedKernel\SmeAccounting.SharedKernel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
  </ItemGroup>

</Project>