<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SmeAccounting.Application\SmeAccounting.Application.csproj" />
    <ProjectReference Include="..\SmeAccounting.Domain\SmeAccounting.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.4" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.12" />
    <PackageReference Include="EFCore.NamingConventions" Version="10.0.*" />
  </ItemGroup>

</Project>
