<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>SmeAccounting.Domain</RootNamespace>
    <AssemblyName>SmeAccounting.Domain</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmeAccounting.SharedKernel\SmeAccounting.SharedKernel.csproj" />
  </ItemGroup>

</Project>