<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>SmeAccounting.Modules.Identity.Application</RootNamespace>
    <AssemblyName>SmeAccounting.Modules.Identity.Application</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Domain/SmeAccounting.Modules.Identity.Domain.csproj" />
    <ProjectReference Include="../../../SmeAccounting.Application/SmeAccounting.Application.csproj" />
    <ProjectReference Include="../../../SmeAccounting.SharedKernel/SmeAccounting.SharedKernel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" />
  </ItemGroup>

</Project>
