<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>SmeAccounting.Modules.Authorization.Infrastructure</RootNamespace>
    <AssemblyName>SmeAccounting.Modules.Authorization.Infrastructure</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Application/SmeAccounting.Modules.Authorization.Application.csproj" />
    <ProjectReference Include="../../Identity/Infrastructure/SmeAccounting.Modules.Identity.Infrastructure.csproj" />
  </ItemGroup>

</Project>
